name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `osk install ...`
        2. Select agent '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output / Logs
      description: If applicable, paste any error messages or logs.
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: e.g., macOS 14.0, Ubuntu 22.04, Windows 11

  - type: dropdown
    id: install-method
    attributes:
      label: Installation Method
      options:
        - npm (global)
        - npx
        - Standalone binary
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: OpenSkill Version
      description: Run `osk version` to get this.
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node --version` to get this (if using npm/npx).
      placeholder: e.g., v20.10.0

  - type: dropdown
    id: agent
    attributes:
      label: Agent (if applicable)
      options:
        - Claude Code
        - Cursor
        - Codex
        - Antigravity
        - N/A

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem.
