name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like osk to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New command
        - New agent support
        - Skill format
        - Repository management
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: agent
    attributes:
      label: Related Agent (if applicable)
      options:
        - All agents
        - Claude Code
        - Cursor
        - Codex
        - Antigravity
        - N/A

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples.
